### ISSUE TITLE
Getting started with Agoric

### ISSUE THREAD

**Issue by danishyasin33** [robor-systems/agoric-amm#1]
Steps to get started with the Agoric project: 
- Read about blockchain and what are smart contracts. Read up specifically on Ethereum and go through its documentation. 
- Learn about smart contracts, dapps, Ether, gas, web2 vs web3, accounts, blocks and transactions
Link: https://ethereum.org/en/developers/docs/

After getting a good understanding of Ethereum, read about Agoric and it's platform: 
- https://agoric.com/

the next step is setup the Agoric CLI, for the CLI, it is required that you use a linux subsystem. If on windows, setup WSL and clone the repo in the linux environment and install all packages. This step is very important. 
- https://agoric.com/documentation/getting-started/before-using-agoric.html#quick-start
- https://github.com/Agoric/agoric-sdk

The final step is to install the agoric-amm dapp created by Robor Systems: 
- https://github.com/robor-systems/agoric-amm

**Comment by Hussain-7** [comment]
## Update 16th December 2021
* Read about `blockchain` and `smart contracts`.
* In depth research through `Ethereum` documentation.
* Went through this Link: https://ethereum.org/en/developers/docs/ thoroughly. 
* Got a good understanding of `agoric and its platform` from the agoric official documentation.
* After that, was able to install `agoric-sdk` and `agoric-cli` successfully on `wsl`.
* Then I ran a demo app that required some `agoric-cli commands` like:
    - agoric init
    - agoric start --reset
    - agoric open --repl
* Finally was able to install and run `agoric-amm` dapp.
* Using Node `v14.17.6`
#### Details about running agoric-amm :
* Commented out line 6 in `src/context/Application.jsx` file
* Commented out line 3 in `src/utils/config.js` file

**Comment by haseebasim** [comment]
**Update 16th December 2021**

- Read and watched videos about **BlockChain**, **Smart Contract**, and **Ethereum**.
- Went through the **Ethereum documentation** thoroughly.
- Explored **agoric** and their website and developed understanding about their organization.
- Explored and installed **WSL** on windows.
- Installed the **agoric-sdk** using the guide provided on their GitHub repository.
- Also ran the **agoric demo app** through the CLI.
- Installed and ran the **agoric-amm** dapp

**Comment by haseebasim** [comment]
Node Version: 16.13.1
Commented out **eslint-disable import/no-mutable-exports** from:

- src/utils/config.js
- src/context/Application.jsx
